require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'abdelrahmanelbakry' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'react-native-headphone-detection', :path => '../node_modules/react-native-headphone-detection'

  pod 'RNAudioJack', :path => '../node_modules/react-native-audio-jack'

  pod 'toolbar-android', :path => '../node_modules/@react-native-community/toolbar-android'

  target 'abdelrahmanelbakryTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'abdelrahmanelbakry-tvOS' do
  # Pods for abdelrahmanelbakry-tvOS

  target 'abdelrahmanelbakry-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
